### ISSUE TITLE
Init pose manager error

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki-x#27]
```
[ERROR] [WallTime: 1400062614.697266] bad callback: <bound method InitPoseManager._initCB of <waiterbot_ctrl_nowireless.init_pose_manager.InitPoseManager object at 0x2cf2510>>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 682, in _invoke_callback
    cb(msg)
  File "/home/yujin/turtlebot/waiterbot/src/kobuki-x/waiterbot_suite/waiterbot_ctrl_nowireless/src/waiterbot_ctrl_nowireless/init_pose_manager.py", line 68, in _initCB
    config = self._client.update_configuration(params)
AttributeError: 'InitPoseManager' object has no attribute '_client'
```

**Comment by bit-pirate** [comment]
Looks like a racing condition. During `_init` `_initCB` can be called before the dynamic reconfigure client is initialised. I'll change the order in `_init`.
